os: Visual Studio 2019
environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python24_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

install:
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python.exe -m pip install pipwin"
  - "%PYTHON%\\Scripts\\pipwin.exe -h"


# build_script:
#   # Build and install the wheel
#   - cd cython
#   - git fetch origin
#   - git checkout %BUILD_COMMIT%
#   # Remove Bazel file that interferes with distutils
#   - del BUILD
#   - python setup.py bdist_wheel
#   - ps: |
#       # Upload artifact to Appveyor immediately after build
#       ls dist -r | Foreach-Object {
#           appveyor PushArtifact $_.FullName
#       }
#   - pip install --pre --no-index -f .\dist cython

# test_script:
#   # Run some tests
#   - ps: get-childitem Demos\*.pyx | foreach-object { cython $_ }
#   - set CFLAGS="/Od"
#   - "%WITH_ENV% %PYTHON%\\python.exe runtests.py -vv --no-cpp --no-code-style -j8"

# after_test:
#   # If tests are successful, create binary packages for the project.
#   - dir dist

# deploy:
#   release: $(BUILD_COMMIT)
#   description: 'Cython $(BUILD_COMMIT)'
#   provider: GitHub
#   auth_token:
#     secure: gIuGypw8TomOL2eG8qqZsICAoSZV0pQMK6BOO8HbQc6bPiKgTnf2kdrTKBvRCdCZ
#   artifact: dist/*.whl
#   draft: false
#   prerelease: false
#   #on:
#     #branch: release                 # release from this branch only
#     #APPVEYOR_REPO_TAG: true          # deploy on tag push only
