name: py
    
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */15 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
      fail-fast: false
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pip setuptools
          pip install requests pendulum beautifulsoup4 lxml csv
          pip install poetry
      - name: execute py script # run the run.py to get the latest data
        run: |
          python /ee_data_stac.py
